### ISSUE TITLE
I have installed the packages from requirements file but when I try to run the chatbot.py file I am getting these errors.

### ISSUE THREAD

**Issue by om-blip** [KirbyDownB/GEICOChatBot#31]
E:\react\GEICOChatBot-master\backend>python chatbot.py
Traceback (most recent call last):
  File "C:\Users\OM\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\srv_resolver.py", line 73, in _resolve_uri
    lifetime=self.__connect_timeout)
  File "C:\Users\OM\AppData\Local\Programs\Python\Python37\lib\site-packages\dns\resolver.py", line 1102, in query
    lifetime)
  File "C:\Users\OM\AppData\Local\Programs\Python\Python37\lib\site-packages\dns\resolver.py", line 1002, in query
    raise NXDOMAIN(qnames=qnames_to_try, responses=nxdomain_responses)
dns.resolver.NXDOMAIN: None of DNS query names exist: _mongodb._tcp.cluster0-jgwg7.mongodb.net., _mongodb._tcp.cluster0-jgwg7.mongodb.net.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chatbot.py", line 14, in <module>
    from new_bot import Bot
  File "E:\react\GEICOChatBot-master\backend\new_bot.py", line 25, in <module>
    "mongodb+srv://adiach1:1234@cluster0-jgwg7.mongodb.net/geico?retryWrites=true&w=majority")
  File "C:\Users\OM\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\mongo_client.py", line 622, in __init__
    connect_timeout=timeout)
  File "C:\Users\OM\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\uri_parser.py", line 463, in parse_uri
    nodes = dns_resolver.get_hosts()
  File "C:\Users\OM\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\srv_resolver.py", line 102, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
  File "C:\Users\OM\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\srv_resolver.py", line 83, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
  File "C:\Users\OM\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\srv_resolver.py", line 79, in _resolve_uri
    raise ConfigurationError(str(exc))
pymongo.errors.ConfigurationError: None of DNS query names exist: _mongodb._tcp.cluster0-jgwg7.mongodb.net., _mongodb._tcp.cluster0-jgwg7.mongodb.net.

**Comment by willshiao** [comment]
You need to change the MongoDB URI to point to your own instance (spin one up first if you don't have one already).

**Comment by om-blip** [comment]
> You need to change the MongoDB URI to point to your own instance (spin one up first if you don't have one already).

Can you guide me on how to do this, I am new to MondoDB.
